### ISSUE TITLE
Checks are grouped together and addressing many rules at the same time

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#163]
**Describe the bug**

The current implementation for OpenDRIVE and OpenSCENARIO XML (__&OTX?_) addressing many rules at the same time. Example from semantic_xodr:

```xml
<Checker status="completed" checkerId="semantic_xodr" description="Evaluates elements in the file and their semantics to guarantee they are in conformity with the standard." summary="">
  <AddressedRule ruleUID="asam.net:xodr:1.7.0:road.lane.level_true_one_side"/>
  <AddressedRule ruleUID="asam.net:xodr:1.7.0:road.lane.access.no_mix_of_deny_or_allow"/>
  <AddressedRule ruleUID="asam.net:xodr:1.4.0:road.lane.link.lanes_across_lane_sections"/>
  <AddressedRule ruleUID="asam.net:xodr:1.4.0:road.linkage.is_junction_needed"/>
  <AddressedRule ruleUID="asam.net:xodr:1.7.0:road.lane.link.zero_width_at_start"/>
  <AddressedRule ruleUID="asam.net:xodr:1.7.0:road.lane.link.zero_width_at_end"/>
  <AddressedRule ruleUID="asam.net:xodr:1.4.0:road.lane.link.new_lane_appear"/>
  <AddressedRule ruleUID="asam.net:xodr:1.4.0:junctions.connection.connect_road_no_incoming_road"/>
  <AddressedRule ruleUID="asam.net:xodr:1.7.0:junctions.connection.one_connection_element"/>
  <AddressedRule ruleUID="asam.net:xodr:1.8.0:junctions.connection.one_link_to_incoming"/>
  <AddressedRule ruleUID="asam.net:xodr:1.7.0:junctions.connection.start_along_linkage"/>
  <AddressedRule ruleUID="asam.net:xodr:1.7.0:junctions.connection.end_opposite_linkage"/>
</Checker>
```

This conflicts with the defintion of a check: https://github.com/asam-ev/qc-framework/blob/3b96d855d836029d857a049dad94e46526e6e8bf/doc/manual/checker_library.md

![image](https://github.com/user-attachments/assets/73b27b58-9b23-4f3a-8081-b9212fc6ff2f)

To group checks together, there is the idea of having checker bundles. _Note: It is ok that the checker libraries has only one checker bundle. But then this one should have many checks._

The biggest issue with the implementation is that without the feature #20, it is not possible to configure the criticality of different rule violations. At the moment, the user need to decide for all rules at the same time, if they should be reported and if the are info, warning or error.

Also the reporting is not clear, because the affected rule is not in focus at the moment.

Currently the structure of checks is aligned with the implementation subdirectories. 

**Expected behavior**

Like the architecture describes: _A check should addresses exactly one rule_.

**Comment by AsamDiegoSanchez** [comment]
According to IVEX the issue can be closed.
