### ISSUE TITLE
Needless focus change (to first row) in source view in ReportGUI when clicking on a found issue

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#173]
**Describe the bug**

A small bug. When click on an issue, the source view always jumps to the file beginning, which is confusing when examine a file.

**To Reproduce**

1. Click on a FileLocation of an issue --> source view goes to the FileLocation 👍 
2. Click on the InertialLocation --> source view stays at the last Filelocation 👍 
3. Click on the issue text (showing a colleague where he should look) --> source view jumps to file beginning 👎 This is bad, because the user still may look into the source code.

![image](https://github.com/user-attachments/assets/2c691ac2-9c8d-494b-902f-e23cda44bb6c)

**Expected behavior**

Just stay, same behavior as when clicking on the InertialLocation

**Comment by AsamDiegoSanchez** [comment]
According to IVEX the issue can be closed (added to already merged PR #187).
