### ISSUE TITLE
Missing Message in ReporGUI when no issues found

### ISSUE THREAD

**Issue by AsamDiegoSanchez** [asam-ev/qc-framework#179]
**Is your feature request related to a problem? Please describe.**
It could be nice if a message could be displayed in the reportGUI when the input files don´t contain any issues, like

"No issues found" or "All correct"

**Describe the solution you'd like**
Message or Pop-Up window containing the information of "No issues found"

**Additional context**
none

**Comment by andreaskern74** [comment]
I think "No issues found" is better than "All correct", because if the framework only finds informational issues, then the input file is also "correct".
