### ISSUE TITLE
Files in directory containing a whitespace don't work when calling ResultPooling, no end result and reporting

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#189]
**Describe the bug**

If the input files and/or the configuration is in a directory containing a whitespace, then there is problem when calling the Result Pooling:

```
Executing result pooling:  ResultPooling
Executing command: cd %ASAM_QC_FRAMEWORK_WORKING_DIR% && C:\conan\qc4openx_internal\2.0.0\fep\testing\package\a2babd8e58b8954fe07ec45125c37cdab96f4789\bin/..\qc-framework\bin\ResultPooling.exe %ASAM_QC_FRAMEWORK_WORKING_DIR% %ASAM_QC_FRAMEWORK_CONFIG_FILE%
Error occurred while executing the command.
Error message:
Invalid number of arguments.
```

Probably because `%ASAM_QC_FRAMEWORK_WORKING_DIR%` and/or `%ASAM_QC_FRAMEWORK_CONFIG_FILE%` contains the whitespace and only the part before is passed as an argument to the `ResultPooling.exe.`

Maybe this can be simply fixed just by improving the Manifest files, but need to be investigated. I've added a complete log and the Manifest Files to this issue.

**To Reproduce**
1. Use the examples from qc-opendrive and replace in one of the folders a `_` with whitespace. Example: `junction_connection_linkage` -->`junction_connection linkage`
2. Create a config file in the same directory
3. Go in this directory and call qc_runtime from there.

* [qc_config.xml](https://github.com/user-attachments/files/17148486/qc_config.xml.txt)
* [framework.json](https://github.com/user-attachments/files/17148520/framework.json)
* [result_pooling.json](https://github.com/user-attachments/files/17148521/result_pooling.json)

**Comment by andreaskern74** [comment]
Additional info: I did a quick test by adapting the `exec_command` in the `result_pooling.json` to

```
"exec_command": "cd \"%ASAM_QC_FRAMEWORK_WORKING_DIR%\" && %QC4OPENX_INTERNAL_DIR%\\qc-framework\\bin\\ResultPooling.exe \"%ASAM_QC_FRAMEWORK_WORKING_DIR%\" %ASAM_QC_FRAMEWORK_CONFIG_FILE%"
```

**Comment by AsamDiegoSanchez** [comment]
Comment from @hoangtungdinh: We will address this one
