### ISSUE TITLE
Root python module `runtime` should be `qc_framework`. `qc_framework` should contain all the necessary to run the framework.

### ISSUE THREAD

**Issue by MatteoRagni** [asam-ev/qc-framework#194]
## Describe the bug

`qc_runtime` python package for framework is distributed with root module name `runtime`. There exists other packages (even pypi [distributed](https://pypi.org/project/runtime/) ones) that ship root modules with same name. Further, modules paths should be descriptive of the content of the package.

Name clashes for root imports should be considered a bug, since they have also some non trivial security implications.

## Expected behavior

There are a couple of consideration on this issue that move the discussion beyond the simple name of the root package:

 1. it can be considered that package users have expectations about the root module to be coherent with package name, i.e., that root package is named `qc_runtime` or `qc_framework`. If the latter is used, package may contain other required modules.
 2. the current repository implements the C++ framework and a python runtime. One of the main objective is to migrate the overall framework to python, leaving only some optional visualization / gui module in C++. A framework install, to be usable (i.e. run with exit 0), has a set of requirements. The set of requirements can be addressed with two modules: 
    
    1. the module `qc_baselib` that contains the models (used by both framework and third party providers for bundles)
    2. the actual framework, which has, as its own minimum requirements:
     
        * runtime, 
        * module that handles manifests (currently included in runtime),
        * at least one pooling system 
        * and at least one report system. 
        * (bundles are effectively optional)
     
    The report and pooling are required by `Configuration` schema. Without them, runtime cannot be executed without errors. It makes little to no sense to not provide at least one result pooling and one report directly with the framework install, and it is advisable to ship a software that is usable out of the box. There are a couple of approach to this, and one suggestion is separating this component in multiple packages. It is easy to understand that this approach creates a situation in which maintenance effort is multiplied, with little to no benefit. Also, from a dependency graph point of view, the approach creates a _circular dependency_ where:

      * runtime package has install dependency on result pooling package and report pooling package (since runtime ships the exec script), 
      * and at the same time pooling and report packages have install dependency on runtime (since they are designed to work only for its flow)

     one solution to avoit circular dependency is to add an additional metapackage for the framework, with install dependency on the three element, at the expense of additional maintenance cost.

## Proposed solution

Modify the current root module to be `qc_framework`, remane package in `qc_framework`, include as submodule `runtime` (and on the same sublevel `report`, as proposed by @hoangtungdinh) to keep the package consistent.

I'll propose the implementation in #191, where it is already needed to succesfully merge the PR.

## Additional context

 * Related to pull request #191, where discussion arised upon content of the framework package vs. content of a runtime only package. In the discussion, some "separation of concerns" are raised about the location of some submodule. The proposed solution is to use a non-standard package configuration with multiple root modules with same name clashes issue. IMHO there is an XY problem here, and this issue should be addressed before continuing that discussion.

**Comment by andreaskern74** [comment]
I'm not the Python expert.... but it makes totally sense.
