### ISSUE TITLE
Rule UID documentation contains examples with invented UID

### ISSUE THREAD

**Issue by MatteoRagni** [asam-ev/qc-framework#22]
**Describe the bug**

The [documentation for Rule UID](https://github.com/asam-ev/qc-framework/pull/19/files#diff-e905e6a52504a776e2fb089db495930eca99be0831b6d389e6bab9dc1dbbff0f) is based upon an UID that was invented at the time of the pull request (#19), because no UID was available at that time.

**Expected behavior**

The documentation should include real and confirmed UIDs, and documentation should be fixed as soon as they become available.

This issue is blocked by PR #19

**Additional Context**

[Discussion](https://github.com/asam-ev/qc-framework/pull/19#discussion_r1514346043) about the topic in PR

**Comment by andreaskern74** [comment]
I checked https://asamev.sharepoint.com/:x:/s/opendrive/ERvWHKaJEbdFlchlYjqMc3YBchN9iCi12ZHz6Te4ocAPdw?e=BUzhzC (line 23). When I understand it right, then there is only super small adaption necessary. 

In https://github.com/asam-ev/qc-framework/blob/3b96d855d836029d857a049dad94e46526e6e8bf/doc/manual/rule_uid_schema.md?plain=1#L92-L117C1

The rule set / id is `asam.net:xodr:1.0.0:road.geometry.refline_exists`  and not `asam.net:xodr:1.6.0:road.planview.geometry.ref_line_exists`, assuming that we had a refline from the first day.

@MircoNierenz : Can you please approve? Thanks.

**Comment by AsamDiegoSanchez** [comment]
According to IVEX the issue can be closed (added to already merged PR #187).
