### ISSUE TITLE
Improve check results with information about addressed rules and meta data

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#25]
**Is your feature request related to a problem? Please describe.**

The current check result container (in base library) and the result file don't contain information about the addressed rules and don't contain meta data information.

**Describe the solution you'd like**

Add information from https://github.com/asam-ev/qc-framework/blob/main/doc/manual/checker_library.md#check-documentation-template
* (list of) addressed rule(s)
* rule version range _(To be clarified if necessary, because rule UIDs contain information about versions)_
* approval information_(To be clarified if necessary, because rule UIDs contain points to official standard or points to a Checker Library specific rule. Official standard rules are always approved by definition. For specific ones.... should be documented at the rule definition, no need in the check result)_
* meta data _(To be clarified if necessary on check and/or on Checker Library level)_
  * key
  * value
  * description

Also related to #35 and #36.

**Comment by pmai** [comment]
Closed with merge of #86.
