### ISSUE TITLE
Report list of addressed rules from result file

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#26]
**Is your feature request related to a problem? Please describe.**

After the result pooling, the result file contain information which checks have ran and which rules they address. The information is there but distributed in the result file. The user wants also to know, which rules are checked by a configuration. The list of ran checks is only an intermediate information to report issues.

This was discussed/requested during the project presentation in ASAM TSC 2024-03-06.

**Describe the solution you'd like**

Form the result file, generate a list of all rule UIDs, which are addressed by the ran checks and a list of rule UIDs, which are violated. As a first solution it is sufficient to add this list to the end of the text report.

**Comment by pmai** [comment]
Closed with merge of #86.
