### ISSUE TITLE
Link to contribution template creates a 404 error 

### ISSUE THREAD

**Issue by TomFleischmann** [asam-ev/qc-framework#31]
**Describe the bug**
On the [contribution guidelines page](https://github.com/asam-ev/qc-framework/blob/main/CONTRIBUTING.md) the link to the template is broken and creates a 404.

...
For most important commits use [commit message template](https://github.com/asam-ev/qc-framework/blob/main/.github/.gitmessage_template)

**Comment by AsamDiegoSanchez** [comment]
We have created some templates if you want to create an issue or report. From my point of view we can delete the whole sentence: "For most important commits use ..."
