### ISSUE TITLE
Python Base Library

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#35]
**Is your feature request related to a problem? Please describe.**

The framework itself supports only C++ at the moment. 
The existing checks for OpenDRIVE and OpenSCENARIO XML are based on Python https://github.com/asam-ev/qc-pyFramework. And we want to have a general Python support in the framework (#15). It shall be possible to implement checks in Python. And this should be as easy as possible.

**Describe the solution you'd like**

Provide a Python base library for the user. This library should also be used in the frame itself (where Python support is implemented).
* read and write configuration file
* read result file
* write result file
  * register check, parameters and metadata
  * add issue with locations (common location types and domain specific) to output container
  * add metadata to output container
  * generate output file base on container

Provide examples
* Read result file: simple report module
* Write result file: simple Checker Bundle with at least two checks, a parameter and a metadata entry

_Note: If modules from the framework itself uses the base library, and if they are documented well, then we don't need additional examples_

**Comment by pmai** [comment]
Closed with merge of #13.
