### ISSUE TITLE
Detect skipped or not run Checkers 

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#45]
## Is your feature request related to a problem? Please describe.

Checkers should be independent, but in reality they are depending on each other. The following picture showing stages of different classes of OpenDRIVE checks. That means, if some more basis checks do not pass, then following higher level checks 
* make no sense to run
* are even not possible to run
* probably run into errors during run

![image](https://github.com/asam-ev/qc-framework/assets/7031041/16d84ab6-69aa-4581-be7d-83c16a2bfe89)

When only writing found issues into the result file, and a Checker could not be run, then it is not clear if there was a precondition not fulfilled or if the input file is valid.

**The user of the framework (or the person who reads the results) shall know if the input file is valid according to specific rules or if it was not possible to evaluate this/run this Checker.**

Additionally, the Framework should be able to identify/detect a mismatch between the workflow configuration (list of Checker Bundles and Checkers) and which Checkers were really executed.

### Result File

The result file should also contain the information, if a Checker was run, if it was skipped or if an error occurred.

_The following specification is only a proposal and might be enhanced._

```xml
(...)
<Checker (…) status="[complete|skipped|error]" summary=”…” >
(...)
```

The `status` contains information if it was run, the `summary` contains additional human-readable information, also depending on the `status`. Example
* complete: _No issues found_ or _Found 23 issues_
* skipped: _Could not be executed because of ..._
* error: _Exception...._

An additional machine-readable status code might be interesting for the future (later).

### Base Libraries

The base libraries (#35 and #36) should support this:

1.  User registers a Checker but does not call `writeResultFile()` --> no content in result file, could be detected by the framework.
2. User only registers Checker but nothing else and call `writeResultFile()` -->  `<Checker X (…) status=”skipped” summary=””/>`, could be detected by the framework.
3. User registers a Checker and report issues --> `<Checker X (…) status=”complete” summary=”Found N issues.”/>`
4. User intentionally skip checker -->  `<Checker X (…) status=”skipped” summary=”because of…”/>`
5. User wants to report an internal error --> `<Checker X (…) status=”error” summary=”because of…”/>`
6. …

## Additional context

This topic is also related to #43 (which has more the focus on the creation of a configuration to prevent these kind of problems).

**Comment by pmai** [comment]
Closed with merge of #86.
