### ISSUE TITLE
Documentation: Add quick start guide

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/qc-framework#83]
**Is your feature request related to a problem? Please describe.**
Currently it is hard to figure out where to start using the framework. Especially how to run the checks is not really clear to me.

**Describe the solution you'd like**
A quick start guide would be great in the documentation, explaining the entire process:

1. Write a configuration file
2. Run the checks according to the configuration file (This step I generally could not find in the doc. Through trial and error I managed to use the runtime.py.)
3. Pool results (is this necessary or done by the framework automatically?)
4. Display the pooled results

The documentation of this should be accompanied by example files, that work out of the box: Example config, example xodr (or xosc) and example checker bundles referenced in the config.

**Additional context**
Related to #38

**Comment by MatteoRagni** [comment]
Hi @ClemensLinnhoff,

for sure we need a quick start guide. The project is lacking one of the topic you mentioned:

> Run the checks according to the configuration file (This step I generally could not find in the doc. Through trial and error I managed to use the runtime.py.)

there is an implementation feature that must be addressed by the project to expose this, namely the implementaiton of the concept of `manifest` of a checker library. We are still discussing its implementation strategy for the first stint of the project. As soon as the project decides the details and performs the initial implementation, I'll try to raise the issue you reported to highest priority.
