### ISSUE TITLE
Remove domain specific RoadLocation issue type from framework

### ISSUE THREAD

**Issue by andreaskern74** [asam-ev/qc-framework#9]
**Is your feature request related to a problem? Please describe.**

The framework shall be independent from specific standards. So, if needed, handling of domain specific things need to be moved to domain specific Checker Libraries.

**Describe the solution you'd like**

Remove the OpenDRIVE specific RoadLocation definition/implementation from the framework.

The name of the remaining `<InertialLocation/>` should be aligned with other standards. It shall describe a point (wtihout direction) in a global Cartesian coordinate system.

**Describe alternatives you've considered**

RaodLocation is not compatible to CRG, OSI or other standards. So we noticed/decided in the sub-group meeting of 2024/02/19 that one location type pointing into a 3D space is enough for the framework.

**Comment by pmai** [comment]
Closed with merge of #86.
