### ISSUE TITLE
Replace short license text in each file with SPDX license identifier

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/qc-framework#94]
**Is your feature request related to a problem? Please describe.**
Currently, the files have a license short text which is not machine readable, like

```CPP
/*
 * This Source Code Form is subject to the terms of the Mozilla
 * Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
 ```

**Describe the solution you'd like**
Replace these short license texts with [SPDX identifiers](https://spdx.org/licenses/), like

```CPP
// SPDX-License-Identifier: MPL-2.0
```

This is a lot shorter and machine readable.

**Comment by MatteoRagni** [comment]
I raise the topicat the next Framework meeting, supporting the request.

**Comment by MatteoRagni** [comment]
We discussed the topic, and even if there is a general agreement on the suggestion you proposed, we need to escalate this to ASAM (the copyright  owner) to have a final decision. We assigned this to @AsamDiegoSanchez.

**Comment by AsamDiegoSanchez** [comment]
We have revised it internally and from ASAM perspective we approve it.

**Comment by andreaskern74** [comment]
Will be implemented in preparation for the official release 1.0.0
