### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/qc-framework#96]
#### Describe the problem
I set up this pull request from a forked repo: #95 
Is it on purpose, that I have the permission to just merge that? Unless I have gotten some special permissions, that means, that anybody could just merge things in the develop branch.

![image](https://github.com/asam-ev/qc-framework/assets/27010086/0afcaabe-255e-44b3-aea2-78143e5b5cad)

**Comment by AsamDiegoSanchez** [comment]
Hi Clemens, thank you for letting me know. We will add a protection mechanism to avoid this situations (Admins can always push. Users with the Maintain role can push when required status checks pass).
Thank you!
